services:
  - type: web
    name: bonziworld
    env: node
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 